apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/add-base-url: "true"
  name: php-ingress
  namespace: php
spec:
    rules:
      - host: php.example.local
        http:
          paths:
          - path: /
            backend:
              serviceName: php-service
              servicePort: 80
